<?xml version="1.0"?>
<package format="2">
    <name>demo_teleop</name>
    <version>0.0.1</version>
    <description>Teleoperation demo for Robotont with ROS 2</description>

    <maintainer email="veiko.vunder@ut.ee">Veiko Vunder</maintainer>
    <maintainer email="karl.kruusamae@ut.ee">Karl Kruusamäe</maintainer>

    <url type="website">https://wiki.ros.org/robotont</url>
    <url type="website">https://robotont.ut.ee</url>
    <url type="repository">https://github.com/robotont-demos/demo_teleop</url>

    <license>Apache 2.0</license>

    <buildtool_depend>ament_cmake</buildtool_depend>
    <exec_depend>launch</exec_depend>
    <exec_depend>launch_ros</exec_depend>
    <exec_depend>ament_index_python</exec_depend>
    <exec_depend>joy</exec_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>

</package>
