axis_linear:
  x: 1
  y: 0
scale_linear:
  x: 0.4
  y: 0.4
scale_linear_turbo:
  x: 1
  y: 1
  yaw: 1.5

axis_angular:
  yaw: 2
scale_angular:
  yaw: 1
scale_angular_turbo:
  yaw: 3

enable_button: 8  # L2 shoulder button
enable_turbo_button: 9  # L1 shoulder button
